### ISSUE TITLE
When to upload the sim

### ISSUE THREAD

**Issue by Geonhee-LEE** [SudeepDasari/visual_foresight#3]
Hello,

I am really interested in visual MPC, but, I don't have Sawyer robot.
Therefore, examples using real robot isn't used for me. I'm looking for usage of simulator in ROS or other simulators.
Can I know when you will upload the sim tutorial?
Thanks.

**Comment by SudeepDasari** [comment]
We aren't planning to add in support for ROS simulators at the moment. Would certainly appreciate if you'd be willing to contribute this feature :) 

Can you not access the environments we have already posted (written in [mujoco-py](https://github.com/openai/mujoco-py). )? While not written with ROS/Gazebo, they are a good way to test visual-mpc in - albeit in a more constrained setting.
