### ISSUE TITLE
Can't find  BaseVideoDataset

### ISSUE THREAD

**Issue by liuem607** [SudeepDasari/visual_foresight#8]
Hi, I tried to use your code in ./examples/dataset_reader.py to read in BAIR Robot Interaction Datasets. But I can't find BaseVideoDataset from visual_mpc/datasets/base_dataset.

**Comment by SudeepDasari** [comment]
Hey,
Thanks for the catch! It seems like the dataset code was erroneously deleted in this repository. I re-pushed the BAIR code into the python file.

You may also be interested in our new robot interaction dataset named [RoboNet](https://www.robonet.wiki/)! It has more robots, more recording viewpoints, and a larger set of train objects.
